name = "gestao-magic"
compatibility_date = "2026-08-10"
[vars]
VITE_SUPABASE_URL = "https://fawlvoiojdgbwpxrojso.supabase.co"
VITE_SUPABASE_ANON_KEY="sb_publishable_C97nCcLIJT7ePhMszo1YmQ_54iFkSX0"
VITE_SUPABASE_PROJECT_ID = "fawlvoiojdgbwpxrojso"
